"""add crop calendar tables

Revision ID: 01121ba72dc9
Revises: 2b9dce44dcd6
Create Date: 2026-07-31 15:31:46.567339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01121ba72dc9'
down_revision: Union[str, Sequence[str], None] = '2b9dce44dcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('land_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.Enum('GROUNDNUT', 'SOYBEAN', 'SESAME', 'MUSTARD', 'SUNFLOWER', 'CASTOR', 'SAFFLOWER', 'LINSEED', 'NIGER', name='crop_calendar_crop'), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['lands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_calendars_land_id'), ['land_id'], unique=False)

    op.create_table('crop_calendar_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('activity_key', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('CROP_ESTABLISHMENT', 'FIELD_MONITORING', 'NUTRIENT_MANAGEMENT', 'IRRIGATION', 'WEED_MANAGEMENT', 'CROP_MONITORING', 'PEST_MONITORING', 'HARVEST_PREPARATION', 'HARVEST', 'POST_HARVEST', name='activity_category'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='activity_priority'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('guidance', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['crop_calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_calendar_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_calendar_activities_calendar_id'), ['calendar_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_calendar_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_calendar_activities_calendar_id'))

    op.drop_table('crop_calendar_activities')
    with op.batch_alter_table('crop_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_calendars_land_id'))

    op.drop_table('crop_calendars')
    # ### end Alembic commands ###
