"""add lands table

Revision ID: 2b9dce44dcd6
Revises: 4b134e51768b
Create Date: 2026-07-31 11:49:46.397394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9dce44dcd6'
down_revision: Union[str, Sequence[str], None] = '4b134e51768b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('farm_location', sa.String(length=255), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.Enum('SANDY', 'LOAMY', 'CLAY', 'RED_SOIL', 'BLACK_SOIL', 'MIXED', 'UNKNOWN', name='soil_type'), nullable=False),
    sa.Column('water_availability', sa.Enum('RELIABLE', 'LIMITED', 'RAIN_FED', 'UNKNOWN', name='water_availability'), nullable=False),
    sa.Column('last_grown_crop', sa.String(length=100), nullable=False),
    sa.Column('planting_season', sa.Enum('KHARIF', 'RABI', 'SUMMER', 'UNKNOWN', name='planting_season'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lands_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lands_user_id'))

    op.drop_table('lands')
    # ### end Alembic commands ###
