"""make firebase uid the primary key, add phone_no

Revision ID: 4b134e51768b
Revises: 42344c854fc6
Create Date: 2026-07-31 11:17:02.198365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b134e51768b'
down_revision: Union[str, Sequence[str], None] = '42344c854fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=20), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.VARCHAR(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
