"""add url column to government_schemes

Revision ID: 5ed75dcba1b7
Revises: e51ce575642c
Create Date: 2026-07-31 17:50:00.296088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed75dcba1b7'
down_revision: Union[str, Sequence[str], None] = 'e51ce575642c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###

    government_schemes_table = sa.table(
        'government_schemes',
        sa.column('slug', sa.String),
        sa.column('url', sa.String),
    )
    urls_by_slug = {
        'e_nam': 'https://enam.gov.in/web/',
        'kcc': 'https://www.jansamarth.in/kisan-credit-card-scheme',
        'nmeo_oilseeds': 'https://nmeo.dac.gov.in/',
        'pm_kisan': 'https://pmkisan.gov.in/',
        'pm_kusum': 'https://pmkusum.mnre.gov.in/',
        'pmfby': 'https://pmfby.gov.in/',
        'soil_health_card': 'https://soilhealth.dac.gov.in/home',
    }
    for slug, url in urls_by_slug.items():
        op.execute(
            government_schemes_table.update()
            .where(government_schemes_table.c.slug == slug)
            .values(url=url)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_schemes', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
