"""add oilseed_prices and price_sync_state tables

Revision ID: b1e6c2b600ad
Revises: 5ed75dcba1b7
Create Date: 2026-08-01 07:26:56.826936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e6c2b600ad'
down_revision: Union[str, Sequence[str], None] = '5ed75dcba1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oilseed_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.Enum('GROUNDNUT', 'SOYBEAN', 'SESAME', 'MUSTARD', 'SUNFLOWER', 'CASTOR', 'SAFFLOWER', 'LINSEED', 'NIGER', name='oilseed_price_crop'), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('price_per_quintal', sa.Float(), nullable=False),
    sa.Column('arrival_metric_tonnes', sa.Float(), nullable=True),
    sa.Column('msp_price', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop', 'reported_date', name='uq_oilseed_price_crop_date')
    )
    with op.batch_alter_table('oilseed_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oilseed_prices_crop'), ['crop'], unique=False)
        batch_op.create_index(batch_op.f('ix_oilseed_prices_reported_date'), ['reported_date'], unique=False)

    op.create_table('price_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_sync_state')
    with op.batch_alter_table('oilseed_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oilseed_prices_reported_date'))
        batch_op.drop_index(batch_op.f('ix_oilseed_prices_crop'))

    op.drop_table('oilseed_prices')
    # ### end Alembic commands ###
