"""add government_schemes table

Revision ID: e51ce575642c
Revises: ffd745b0fbe3
Create Date: 2026-07-31 17:20:11.740738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51ce575642c'
down_revision: Union[str, Sequence[str], None] = 'ffd745b0fbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1500), nullable=False),
    sa.Column('eligibility_summary', sa.String(length=1500), nullable=False),
    sa.Column('key_benefit', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_schemes_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_government_schemes_state'), ['state'], unique=False)

    # ### end Alembic commands ###

    # Seed the 7 central schemes checked against public web sources on 2026-07-31
    # (see app/services/scheme_recommendation.py history for source links). No
    # state-specific schemes are seeded here — those need to be sourced first.
    government_schemes_table = sa.table(
        'government_schemes',
        sa.column('slug', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('eligibility_summary', sa.String),
        sa.column('key_benefit', sa.String),
        sa.column('state', sa.String),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(government_schemes_table, [
        {
            'slug': 'pm_kisan',
            'name': 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
            'description': (
                'Central income-support scheme paying ₹6,000/year (three '
                '₹2,000 installments, roughly Apr–Jul, Aug–Nov, '
                'Dec–Mar) directly to the bank accounts of landholding '
                'farmer families, via DBT.'
            ),
            'eligibility_summary': (
                'All landholding farmer families are eligible, regardless of '
                'landholding size, subject to e-KYC and Aadhaar-linked bank '
                'account verification. Excluded: institutional landholders, '
                'families with a member holding a constitutional post or a '
                'serving/retired senior government employee, income-tax '
                'payers, and registered professionals (doctors, engineers, '
                'CAs). We do not collect income, employment, or '
                'professional-registration data, so these exclusions can '
                'never be confirmed from our records alone.'
            ),
            'key_benefit': '₹6,000/year direct income support, paid in 3 installments.',
            'state': 'central',
            'is_active': True,
        },
        {
            'slug': 'pmfby',
            'name': 'PMFBY (Pradhan Mantri Fasal Bima Yojana)',
            'description': (
                'Crop insurance covering yield loss from natural calamities, '
                'pests, and disease, for notified crops in notified '
                'districts/seasons. Farmer premium is capped at 2% for '
                'kharif crops, 1.5% for rabi crops, and 5% for '
                'commercial/horticultural crops — Centre and State '
                'jointly subsidize the rest of the actuarial premium. '
                'Enrollment has been voluntary for all farmers since 2020.'
            ),
            'eligibility_summary': (
                'Both loanee and non-loanee farmers growing a notified crop '
                'in a notified area/season are eligible. We do not have the '
                'state/district-wise notified-crop list, so we can only say '
                "whether the farmer's crop is generally the type PMFBY "
                'covers (it covers most food and oilseed crops), not '
                'confirm actual notification status for their specific '
                'area and season.'
            ),
            'key_benefit': (
                'Low-premium insurance (1.5-2% of sum insured) against '
                'yield loss from weather, pests, or disease.'
            ),
            'state': 'central',
            'is_active': True,
        },
        {
            'slug': 'kcc',
            'name': 'KCC (Kisan Credit Card)',
            'description': (
                'Gives farmers short-term credit for cultivation and '
                'post-harvest expenses and working capital as a revolving '
                'credit line. Base rate ~7% per annum, reduced to an '
                'effective ~4% per annum with government interest '
                'subvention (2%) plus a Prompt Repayment Incentive (3%) for '
                'farmers who repay on time. No collateral required up to '
                '₹1.60 lakh; the interest-subvention loan ceiling was '
                'raised to ₹5 lakh in the 2025-26 Union Budget.'
            ),
            'eligibility_summary': (
                'Owner-cultivators, tenant farmers, sharecroppers, oral '
                'lessees, and also fishermen/dairy farmers under allied KCC '
                'variants, are generally eligible; no crop or income '
                'restriction. Requires proof of landholding certified by '
                'revenue authorities.'
            ),
            'key_benefit': 'Short-term agricultural credit at an effective ~4% interest via a revolving credit card.',
            'state': 'central',
            'is_active': True,
        },
        {
            'slug': 'pm_kusum',
            'name': 'PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan)',
            'description': (
                'Subsidizes standalone solar irrigation pumps (Component B, '
                '3-10 HP) and solarization of existing grid-connected pumps '
                '(Component C), plus setting up small solar power plants on '
                'barren/fallow land (Component A), reducing dependence on '
                'grid power or diesel for irrigation. Subsidy is commonly '
                'up to 60% (30% central + 30% state contribution, varying '
                'by state — some northeastern/hilly states go up to '
                '80%), with an additional 30% available as a '
                'government-backed loan in many states. Exact subsidy '
                "split and application windows are set independently by "
                "each state's nodal agency, not a single national form."
            ),
            'eligibility_summary': (
                'Open to individual farmers, farmer groups, cooperatives, '
                'and panchayats owning agricultural land who want to '
                'install or solarize an irrigation pump; most valuable to '
                'farmers currently rain_fed or on limited water '
                'availability who lack reliable irrigation. Scheme '
                'end-date and state-level windows change periodically '
                '— confirm current status before relying on this.'
            ),
            'key_benefit': 'Subsidy (commonly ~60%, more in some states) on solar irrigation pumps/power plants.',
            'state': 'central',
            'is_active': True,
        },
        {
            'slug': 'soil_health_card',
            'name': 'Soil Health Card Scheme',
            'description': (
                'Provides farmers a Soil Health Card, reissued roughly '
                'every two years, showing soil nutrient status across 12 '
                'parameters plus crop-wise fertilizer/nutrient '
                'recommendations, based on free soil testing. Over 25.89 '
                'crore cards have been issued nationwide as of mid-2026. '
                'Typically improves yield ~10-15% and cuts fertilizer cost '
                '~20-30% when farmers follow the recommendations.'
            ),
            'eligibility_summary': 'Universally available to any farmer with cultivable land; no exclusions.',
            'key_benefit': 'Free soil testing plus tailored fertilizer/nutrient-dose guidance.',
            'state': 'central',
            'is_active': True,
        },
        {
            'slug': 'nmeo_oilseeds',
            'name': 'NMEO-Oilseeds (National Mission on Edible Oils – Oilseeds)',
            'description': (
                '7-year mission (2024-25 to 2030-31, ₹10,103 crore '
                'outlay) to raise domestic oilseed production, targeting '
                'an increase from 39 million tonnes (2022-23) to 69.7 '
                'million tonnes by 2030-31, via certified/hybrid seed '
                'mini-kits, cluster demonstrations, and input support. '
                'Focus is primarily rapeseed-mustard, groundnut, soybean, '
                'sunflower, and sesame, plus secondary sources like '
                'cottonseed and rice bran. Also promotes expanding oilseed '
                'cultivation onto rice/potato fallow land and intercropping.'
            ),
            'eligibility_summary': (
                'Farmers currently growing, or willing to grow, any of the '
                'primary oilseed crops this mission covers (mustard, '
                'groundnut, soybean, sunflower, sesame) are the direct '
                'target group. The remaining crops tracked in this app '
                '(castor, safflower, linseed, niger) are not named as '
                'primary focus crops in the mission, so relevance for '
                'those is weaker/indirect.'
            ),
            'key_benefit': 'Subsidized seed mini-kits, cluster demonstrations, and input support for oilseed cultivation.',
            'state': 'central',
            'is_active': True,
        },
        {
            'slug': 'e_nam',
            'name': 'e-NAM (National Agriculture Market)',
            'description': (
                'Pan-India electronic trading platform networking APMC '
                'mandis (1,656 mandis across 23 states + 4 UTs as of March '
                '2026), giving farmers access to buyers beyond their local '
                'mandi, transparent online bidding, and direct electronic '
                'payment. Covers 247 tradable commodities.'
            ),
            'eligibility_summary': (
                'Any farmer with produce to sell can register (typically '
                'via their local APMC mandi) and trade on e-NAM; no crop '
                'or landholding restriction.'
            ),
            'key_benefit': 'Wider buyer access and transparent price discovery when selling produce.',
            'state': 'central',
            'is_active': True,
        },
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_schemes_state'))
        batch_op.drop_index(batch_op.f('ix_government_schemes_slug'))

    op.drop_table('government_schemes')
    # ### end Alembic commands ###
