"""replace oilseed_prices with commodity_prices for all commodities

Revision ID: fc805d0d55e0
Revises: b1e6c2b600ad
Create Date: 2026-08-01 08:13:53.432346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc805d0d55e0'
down_revision: Union[str, Sequence[str], None] = 'b1e6c2b600ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_name', sa.String(length=255), nullable=False),
    sa.Column('commodity_group', sa.String(length=100), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('price_per_quintal', sa.Float(), nullable=False),
    sa.Column('arrival_metric_tonnes', sa.Float(), nullable=True),
    sa.Column('msp_price', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_name', 'reported_date', name='uq_commodity_price_name_date')
    )
    with op.batch_alter_table('commodity_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_prices_commodity_group'), ['commodity_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_prices_commodity_name'), ['commodity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_prices_reported_date'), ['reported_date'], unique=False)

    with op.batch_alter_table('oilseed_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oilseed_prices_crop'))
        batch_op.drop_index(batch_op.f('ix_oilseed_prices_reported_date'))

    op.drop_table('oilseed_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oilseed_prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crop', sa.VARCHAR(length=9), nullable=False),
    sa.Column('reported_date', sa.DATE(), nullable=False),
    sa.Column('price_per_quintal', sa.FLOAT(), nullable=False),
    sa.Column('arrival_metric_tonnes', sa.FLOAT(), nullable=True),
    sa.Column('msp_price', sa.FLOAT(), nullable=True),
    sa.Column('trend', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop', 'reported_date', name=op.f('uq_oilseed_price_crop_date'))
    )
    with op.batch_alter_table('oilseed_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oilseed_prices_reported_date'), ['reported_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_oilseed_prices_crop'), ['crop'], unique=False)

    with op.batch_alter_table('commodity_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_prices_reported_date'))
        batch_op.drop_index(batch_op.f('ix_commodity_prices_commodity_name'))
        batch_op.drop_index(batch_op.f('ix_commodity_prices_commodity_group'))

    op.drop_table('commodity_prices')
    # ### end Alembic commands ###
